live_config_reload = true

[font]
size = 16

[env]
TERM = "alacritty"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"


[window]
dynamic_padding = false
opacity = 0.6

[font.normal]
family = "Agave Nerd Font Mono"
style = "Regular"
